# Generated by Django 4.0 on 2021-12-27 21:18

from django.db import migrations, models
import uuid
import webui.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to=webui.models.content_single_image_name)),
                ('imageid', models.CharField(blank=True, default=uuid.uuid4, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
